/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dakmainstitute.view;

import com.sun.org.apache.xerces.internal.dom.PSVIAttrNSImpl;
import dakmainstitute.controller.SubjectController;
import dakmainstitute.controller.TestController;
import dakmainstitute.controller.TestMarksController;
import dakmainstitute.model.Subject;
import dakmainstitute.model.Test;
import dakmainstitute.model.TestMarks;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jfreechart.ViewGirlsBoysAvgChart;

/**
 *
 * @author Shashi
 */
public class ViewAvgChartForm extends JDialog {

    /**
     * Creates new form ViewAvgChartForm
     */
    DefaultTableModel dtm;

    public ViewAvgChartForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        try {
            fillSubjectCombo();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ViewAvgChartForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel dtm = (DefaultTableModel) avgTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linkModel1 = new org.jdesktop.swingx.hyperlink.LinkModel();
        lookAndFeelUtils1 = new org.jdesktop.swingx.plaf.LookAndFeelUtils();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jXFrame1 = new org.jdesktop.swingx.JXFrame();
        jPanel1 = new javax.swing.JPanel();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jPanel2 = new javax.swing.JPanel();
        testTypeCombo = new javax.swing.JComboBox();
        subjectCombo = new javax.swing.JComboBox();
        classText = new javax.swing.JTextField();
        classLabel = new javax.swing.JLabel();
        testTypeLabel1 = new javax.swing.JLabel();
        districtCombo = new javax.swing.JComboBox();
        lineChartLabel = new org.jdesktop.swingx.JXLabel();
        testTypeLabel2 = new javax.swing.JLabel();
        testTypeLabel3 = new javax.swing.JLabel();
        layerdChartLabel = new org.jdesktop.swingx.JXLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        avgTable = new org.jdesktop.swingx.JXTable();

        javax.swing.GroupLayout jXFrame1Layout = new javax.swing.GroupLayout(jXFrame1.getContentPane());
        jXFrame1.getContentPane().setLayout(jXFrame1Layout);
        jXFrame1Layout.setHorizontalGroup(
            jXFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jXFrame1Layout.setVerticalGroup(
            jXFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jXPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 3, true));

        testTypeCombo.setBackground(new java.awt.Color(153, 204, 255));
        testTypeCombo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        testTypeCombo.setForeground(new java.awt.Color(153, 0, 0));
        testTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Revision", "Theory" }));
        testTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testTypeComboActionPerformed(evt);
            }
        });
        testTypeCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                testTypeComboKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                testTypeComboKeyReleased(evt);
            }
        });

        subjectCombo.setBackground(new java.awt.Color(153, 204, 255));
        subjectCombo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        subjectCombo.setForeground(new java.awt.Color(204, 0, 0));
        subjectCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectComboActionPerformed(evt);
            }
        });
        subjectCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subjectComboKeyPressed(evt);
            }
        });

        classText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        classText.setForeground(new java.awt.Color(204, 0, 0));
        classText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classTextActionPerformed(evt);
            }
        });
        classText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                classTextKeyPressed(evt);
            }
        });

        classLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        classLabel.setForeground(new java.awt.Color(102, 0, 102));
        classLabel.setText("Class       :");

        testTypeLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        testTypeLabel1.setForeground(new java.awt.Color(102, 0, 102));
        testTypeLabel1.setText("Test Type:");

        districtCombo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        districtCombo.setForeground(new java.awt.Color(204, 0, 0));
        districtCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matara", "Galle", "Thangalla" }));
        districtCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtComboActionPerformed(evt);
            }
        });
        districtCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                districtComboKeyPressed(evt);
            }
        });

        lineChartLabel.setBackground(new java.awt.Color(255, 255, 255));
        lineChartLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dakmainstitute/icon/line_chart-48.png"))); // NOI18N
        lineChartLabel.setText(" View Line Chart");
        lineChartLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lineChartLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lineChartLabel.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);
        lineChartLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lineChartLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lineChartLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lineChartLabelMouseExited(evt);
            }
        });

        testTypeLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        testTypeLabel2.setForeground(new java.awt.Color(102, 0, 102));
        testTypeLabel2.setText("Subject    :");

        testTypeLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        testTypeLabel3.setForeground(new java.awt.Color(102, 0, 102));
        testTypeLabel3.setText("District    :");

        layerdChartLabel.setBackground(new java.awt.Color(255, 255, 255));
        layerdChartLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dakmainstitute/icon/templateRealAppWizBanner.png"))); // NOI18N
        layerdChartLabel.setText("View Layerd Chart");
        layerdChartLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        layerdChartLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        layerdChartLabel.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);
        layerdChartLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        layerdChartLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                layerdChartLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                layerdChartLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                layerdChartLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layerdChartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineChartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(testTypeLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(classLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(classText, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(testTypeLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(subjectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(testTypeLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(testTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(districtCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {layerdChartLabel, lineChartLabel});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(classText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classLabel)
                            .addComponent(testTypeLabel3)
                            .addComponent(districtCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(testTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(testTypeLabel1)
                            .addComponent(subjectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(testTypeLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(layerdChartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineChartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {layerdChartLabel, lineChartLabel});

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        avgTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        avgTable.setGridColor(new java.awt.Color(204, 204, 255));
        avgTable.setRowHeight(25);
        jScrollPane1.setViewportView(avgTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void layerdChartLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_layerdChartLabelMouseEntered
        layerdChartLabel.setBackground(Color.CYAN);
    }//GEN-LAST:event_layerdChartLabelMouseEntered

    private void layerdChartLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_layerdChartLabelMouseExited
        layerdChartLabel.setBackground(Color.white);
    }//GEN-LAST:event_layerdChartLabelMouseExited

    private void lineChartLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineChartLabelMouseEntered
        lineChartLabel.setBackground(Color.CYAN);
    }//GEN-LAST:event_lineChartLabelMouseEntered

    private void lineChartLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineChartLabelMouseExited
        lineChartLabel.setBackground(Color.white);
    }//GEN-LAST:event_lineChartLabelMouseExited

    private void classTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classTextActionPerformed

    }//GEN-LAST:event_classTextActionPerformed

    private void classTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classTextKeyPressed
        if (evt.getKeyCode() == 10) {
            String clz = classText.getText();
            classText.setText(clz + "A/L");
            subjectCombo.requestFocus();
        }
    }//GEN-LAST:event_classTextKeyPressed

    private void subjectComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectComboActionPerformed

    }//GEN-LAST:event_subjectComboActionPerformed

    private void subjectComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subjectComboKeyPressed
        if (evt.getKeyCode() == 10) {
            districtCombo.requestFocus();
        }
    }//GEN-LAST:event_subjectComboKeyPressed

    private void testTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testTypeComboActionPerformed

    }//GEN-LAST:event_testTypeComboActionPerformed

    private void testTypeComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_testTypeComboKeyPressed
        if (evt.getKeyCode() == 10) {

            dtm = (DefaultTableModel) avgTable.getModel();
            ArrayList<Test> testList = null;
            try {
                testList = TestController.getTestId(classText.getText(), subjectCombo.getSelectedItem() + "", testTypeCombo.getSelectedItem() + "");
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ViewAvgChartForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            int possision = 0;
            for (Test test : testList) {

                Object[] row = {test.getTestId()};
                dtm.addRow(row);
                try {
                    int count = 0;
                    double total = 0;
                    double boysTotal = 0;
                    double girlsTotal = 0;
                    List<Double> list = new ArrayList<>();
                    ArrayList<TestMarks> testMarksList = TestMarksController.getStudentMarks(test.getTestId(), districtCombo.getSelectedItem() + "");
                    for (TestMarks testMarks : testMarksList) {
                        total += Double.parseDouble(testMarks.getMarks() + "");
                        list.add(Double.parseDouble(testMarks.getMarks() + ""));
                        count++;
                    }
                    String totAvg = total / count + "";
                    dtm.setValueAt(totAvg, possision, 1);

                    int girlsCount = 0;
                    int boysCount = 0;
                    List<Double> boysList = new ArrayList<>();
                    for (TestMarks testMarks : testMarksList) {
                        String index = testMarks.getIndexNo();
                        char ch = index.charAt(2);
                        if (ch == 'B') {
                            boysTotal += Double.parseDouble(testMarks.getMarks() + "");
                            boysList.add(Double.parseDouble(testMarks.getMarks() + ""));
                            boysCount++;
                        }
                    }
                    String boysAvg = boysTotal / boysCount + "";
                    dtm.setValueAt(boysAvg, possision, 3);

                    List<Double> girlsList = new ArrayList<>();
                    for (TestMarks testMarks : testMarksList) {
                        String index = testMarks.getIndexNo();
                        char ch = index.charAt(2);
                        if (ch == 'G') {
                            girlsTotal += Double.parseDouble(testMarks.getMarks() + "");
                            girlsList.add(Double.parseDouble(testMarks.getMarks() + ""));
                            girlsCount++;
                        }
                    }
                    String girlsAvg = girlsTotal / girlsCount + "";
                    dtm.setValueAt(girlsAvg, possision, 2);

                    possision++;

                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ViewAvgChartForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_testTypeComboKeyPressed

    private void testTypeComboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_testTypeComboKeyReleased

    }//GEN-LAST:event_testTypeComboKeyReleased

    private void districtComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtComboActionPerformed
        testTypeCombo.requestFocus();
    }//GEN-LAST:event_districtComboActionPerformed

    private void districtComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_districtComboKeyPressed
        if (evt.getKeyCode() == 10) {
            testTypeCombo.requestFocus();
        }
    }//GEN-LAST:event_districtComboKeyPressed

    private void layerdChartLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_layerdChartLabelMouseClicked
        List<Double> gList = new ArrayList<>();
        for (int i = 0; i < avgTable.getRowCount(); i++) {
            gList.add(Double.parseDouble(avgTable.getValueAt(i, 2) + ""));
        }
        //try {
            //ViewGirlsBoysAvgChart.viweGirlsAvgChart(gList);
       // } catch (SQLException ex) {
            //Logger.getLogger(ViewAvgChartForm.class.getName()).log(Level.SEVERE, null, ex);
        //} catch (ClassNotFoundException ex) {
            //Logger.getLogger(ViewAvgChartForm.class.getName()).log(Level.SEVERE, null, ex);
        //}
    }//GEN-LAST:event_layerdChartLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAvgChartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAvgChartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAvgChartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAvgChartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewAvgChartForm dialog = new ViewAvgChartForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTable avgTable;
    private javax.swing.JLabel classLabel;
    private javax.swing.JTextField classText;
    private javax.swing.JComboBox districtCombo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXFrame jXFrame1;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXLabel layerdChartLabel;
    private org.jdesktop.swingx.JXLabel lineChartLabel;
    private org.jdesktop.swingx.hyperlink.LinkModel linkModel1;
    private org.jdesktop.swingx.plaf.LookAndFeelUtils lookAndFeelUtils1;
    private javax.swing.JComboBox subjectCombo;
    private javax.swing.JComboBox testTypeCombo;
    private javax.swing.JLabel testTypeLabel1;
    private javax.swing.JLabel testTypeLabel2;
    private javax.swing.JLabel testTypeLabel3;
    // End of variables declaration//GEN-END:variables
    private void fillSubjectCombo() throws SQLException, ClassNotFoundException {
        ArrayList<Subject> subjectList = SubjectController.getAllSubject();
        //subjectList.removeAllItems();
        for (Subject subject : subjectList) {
            subjectCombo.addItem(subject);

        }
    }
}
