/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dakmainstitute.view;

import dakmainstitute.controller.ReportController;
import dakmainstitute.controller.StudentController;
import dakmainstitute.controller.SubjectController;
import dakmainstitute.controller.TestController;
import dakmainstitute.controller.TestMarksController;
import dakmainstitute.model.Subject;
import dakmainstitute.model.Test;
import dakmainstitute.model.TestMarks;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;

/**
 *
 * @author Shashi
 */
public class ViewRanges extends JInternalFrame {

    /**
     * Creates new form ViewRanges
     */
    int possision;
    DefaultTableModel dtm;

    public ViewRanges(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
        try {
            fillSubjectCombo();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ViewRanges.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        layerdChartLabel = new org.jdesktop.swingx.JXLabel();
        lineChartLabel = new org.jdesktop.swingx.JXLabel();
        classLabel = new javax.swing.JLabel();
        classText = new javax.swing.JTextField();
        testTypeLabel2 = new javax.swing.JLabel();
        subjectCombo = new javax.swing.JComboBox();
        testTypeLabel1 = new javax.swing.JLabel();
        testTypeCombo = new javax.swing.JComboBox();
        testTypeLabel3 = new javax.swing.JLabel();
        districtCombo = new javax.swing.JComboBox();
        testIdCombo = new javax.swing.JComboBox();
        testTypeLabel4 = new javax.swing.JLabel();
        testTypeLabel5 = new javax.swing.JLabel();
        firstRangeText = new javax.swing.JTextField();
        secondRangeText = new javax.swing.JTextField();
        testTypeLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rangesTabel = new javax.swing.JTable();
        viewButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();

        jPanel1.setBackground(java.awt.Color.white);

        jXPanel1.setBackground(new java.awt.Color(255, 255, 255));

        layerdChartLabel.setBackground(new java.awt.Color(255, 255, 255));
        layerdChartLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dakmainstitute/icon/templateRealAppWizBanner.png"))); // NOI18N
        layerdChartLabel.setText("View Layerd Chart");
        layerdChartLabel.setToolTipText("View layerd chart of student's marks avarage");
        layerdChartLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        layerdChartLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        layerdChartLabel.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);
        layerdChartLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        layerdChartLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                layerdChartLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                layerdChartLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                layerdChartLabelMouseExited(evt);
            }
        });

        lineChartLabel.setBackground(new java.awt.Color(255, 255, 255));
        lineChartLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dakmainstitute/icon/line_chart-48.png"))); // NOI18N
        lineChartLabel.setText(" View Line Chart");
        lineChartLabel.setToolTipText("View line chart of student's marks avarage");
        lineChartLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lineChartLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lineChartLabel.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);
        lineChartLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lineChartLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lineChartLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lineChartLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lineChartLabelMouseExited(evt);
            }
        });

        classLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        classLabel.setText("Class       :");

        classText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        classText.setForeground(new java.awt.Color(102, 0, 0));
        classText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classTextActionPerformed(evt);
            }
        });
        classText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                classTextKeyPressed(evt);
            }
        });

        testTypeLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        testTypeLabel2.setText("Subject    :");

        subjectCombo.setBackground(new java.awt.Color(153, 204, 255));
        subjectCombo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        subjectCombo.setForeground(new java.awt.Color(102, 0, 0));
        subjectCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectComboActionPerformed(evt);
            }
        });
        subjectCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subjectComboKeyPressed(evt);
            }
        });

        testTypeLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        testTypeLabel1.setText("Test Type:");

        testTypeCombo.setBackground(new java.awt.Color(153, 204, 255));
        testTypeCombo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        testTypeCombo.setForeground(new java.awt.Color(102, 0, 0));
        testTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Revision", "Theory" }));
        testTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testTypeComboActionPerformed(evt);
            }
        });
        testTypeCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                testTypeComboKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                testTypeComboKeyReleased(evt);
            }
        });

        testTypeLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        testTypeLabel3.setText("District    :");

        districtCombo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        districtCombo.setForeground(new java.awt.Color(102, 0, 102));
        districtCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matara", "Galle", "Thangalla" }));
        districtCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtComboActionPerformed(evt);
            }
        });
        districtCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                districtComboKeyPressed(evt);
            }
        });

        testIdCombo.setBackground(new java.awt.Color(153, 204, 255));
        testIdCombo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        testIdCombo.setForeground(new java.awt.Color(102, 0, 0));
        testIdCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                testIdComboItemStateChanged(evt);
            }
        });
        testIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testIdComboActionPerformed(evt);
            }
        });
        testIdCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                testIdComboKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                testIdComboKeyReleased(evt);
            }
        });

        testTypeLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        testTypeLabel4.setText("Test Id :");

        testTypeLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        testTypeLabel5.setText("Input Range:");

        firstRangeText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstRangeText.setForeground(new java.awt.Color(204, 0, 0));
        firstRangeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstRangeTextActionPerformed(evt);
            }
        });

        secondRangeText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secondRangeText.setForeground(new java.awt.Color(204, 0, 0));
        secondRangeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondRangeTextActionPerformed(evt);
            }
        });

        testTypeLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        testTypeLabel6.setText("-");

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel1Layout.createSequentialGroup()
                        .addComponent(layerdChartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineChartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testTypeLabel2)
                            .addComponent(classLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classText, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subjectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(testTypeLabel3)
                            .addComponent(testTypeLabel1))
                        .addGap(10, 10, 10)
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(districtCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(testTypeLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(testIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(testTypeLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstRangeText, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(testTypeLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(secondRangeText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jXPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {firstRangeText, secondRangeText});

        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(layerdChartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineChartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jXPanel1Layout.createSequentialGroup()
                                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(testTypeLabel3)
                                    .addComponent(districtCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(testTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(testTypeLabel1)))
                            .addGroup(jXPanel1Layout.createSequentialGroup()
                                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(classLabel)
                                    .addComponent(classText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(subjectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(testTypeLabel2))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testTypeLabel4)
                    .addComponent(testTypeLabel5)
                    .addComponent(firstRangeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondRangeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testTypeLabel6))
                .addGap(24, 24, 24))
        );

        jXPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {firstRangeText, secondRangeText});

        rangesTabel.setForeground(new java.awt.Color(102, 102, 102));
        rangesTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Range", "Student Count", "Precentage (%)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rangesTabel.setRowHeight(25);
        jScrollPane1.setViewportView(rangesTabel);

        viewButton.setBackground(new java.awt.Color(153, 153, 255));
        viewButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewButton.setText("View Schools precentage");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        printButton.setBackground(new java.awt.Color(255, 204, 204));
        printButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dakmainstitute/icon/bottom_navigation_toolbar-26.png"))); // NOI18N
        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(printButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void layerdChartLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_layerdChartLabelMouseClicked

    }//GEN-LAST:event_layerdChartLabelMouseClicked

    private void layerdChartLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_layerdChartLabelMouseEntered
        layerdChartLabel.setBackground(Color.CYAN);
    }//GEN-LAST:event_layerdChartLabelMouseEntered

    private void layerdChartLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_layerdChartLabelMouseExited
        layerdChartLabel.setBackground(Color.white);
    }//GEN-LAST:event_layerdChartLabelMouseExited

    private void lineChartLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineChartLabelMouseClicked

    }//GEN-LAST:event_lineChartLabelMouseClicked

    private void lineChartLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineChartLabelMouseEntered
        lineChartLabel.setBackground(Color.CYAN);
    }//GEN-LAST:event_lineChartLabelMouseEntered

    private void lineChartLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineChartLabelMouseExited
        lineChartLabel.setBackground(Color.white);
    }//GEN-LAST:event_lineChartLabelMouseExited

    private void classTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classTextActionPerformed

    }//GEN-LAST:event_classTextActionPerformed

    private void classTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classTextKeyPressed
        if (evt.getKeyCode() == 10) {
            String clz = classText.getText();
            try {
                boolean b = StudentController.isClassAvailable(clz + "A/L");
                if (b == true) {
                    classText.setText(clz + "A/L");
                    subjectCombo.requestFocus();
                } else {
                    classText.setText("");

                }

            } catch (    SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ViewRanges.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_classTextKeyPressed

    private void subjectComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectComboActionPerformed

    }//GEN-LAST:event_subjectComboActionPerformed

    private void subjectComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subjectComboKeyPressed
        if (evt.getKeyCode() == 10) {
            districtCombo.requestFocus();
        }
    }//GEN-LAST:event_subjectComboKeyPressed

    private void testTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testTypeComboActionPerformed

    }//GEN-LAST:event_testTypeComboActionPerformed

    private void testTypeComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_testTypeComboKeyPressed
        if (evt.getKeyCode() == 10) {
            try {
                fillTestIdCombo();
            } catch (    SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ViewRanges.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        testIdCombo.requestFocus();
    }//GEN-LAST:event_testTypeComboKeyPressed

    private void testTypeComboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_testTypeComboKeyReleased

    }//GEN-LAST:event_testTypeComboKeyReleased

    private void districtComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtComboActionPerformed
        testTypeCombo.requestFocus();
    }//GEN-LAST:event_districtComboActionPerformed

    private void districtComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_districtComboKeyPressed
        if (evt.getKeyCode() == 10) {
            testTypeCombo.requestFocus();
        }
    }//GEN-LAST:event_districtComboKeyPressed

    private void testIdComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_testIdComboItemStateChanged

    }//GEN-LAST:event_testIdComboItemStateChanged

    private void testIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testIdComboActionPerformed
        firstRangeText.requestFocus();
    }//GEN-LAST:event_testIdComboActionPerformed

    private void testIdComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_testIdComboKeyPressed
        firstRangeText.requestFocus();
    }//GEN-LAST:event_testIdComboKeyPressed

    private void testIdComboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_testIdComboKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_testIdComboKeyReleased

    private void firstRangeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstRangeTextActionPerformed
        secondRangeText.requestFocus();
    }//GEN-LAST:event_firstRangeTextActionPerformed

    private void secondRangeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondRangeTextActionPerformed
        dtm = (DefaultTableModel) rangesTabel.getModel();

        String testId = testIdCombo.getSelectedItem() + "";
        ArrayList<TestMarks> stuList = null;
        try {
            stuList = TestMarksController.getStudentCountOfRanges(testId, firstRangeText.getText(), secondRangeText.getText());
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ViewAvgChartForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        double allOfStudentsCount = 0;
        try {
            allOfStudentsCount = Integer.parseInt(TestMarksController.getAllOfStudentsCount(testIdCombo.getSelectedItem() + ""));
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ViewRanges.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (TestMarks testMarks : stuList) {

            String range = firstRangeText.getText() + " - " + secondRangeText.getText();

            double count = Double.parseDouble(testMarks.getCount());
            double precentage = (count / allOfStudentsCount) * 100;
            
            
            Object[] rows = {range, (int)count,precentage};
            dtm.addRow(rows);

        }
        firstRangeText.setText("");
        secondRangeText.setText("");
        firstRangeText.requestFocus();
    }//GEN-LAST:event_secondRangeTextActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        String testId = testIdCombo.getSelectedItem() + "";

        new PrecentageOfSchoolsGetA(testId).setVisible(true);
    }//GEN-LAST:event_viewButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
            Map<String, Object> params = new HashMap<>();
            params.put("TESTID", testIdCombo.getSelectedItem().toString());
            params.put("DISTRICT", districtCombo.getSelectedItem().toString());
           
            JRTableModelDataSource ds = new JRTableModelDataSource(rangesTabel.getModel());

            ReportController.viewReport(params, "./src/dakmainstitiute/reports/MarksOfRange.jrxml", ds);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRanges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRanges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRanges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRanges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ViewRanges(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel classLabel;
    private javax.swing.JTextField classText;
    private javax.swing.JComboBox districtCombo;
    private javax.swing.JTextField firstRangeText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXLabel layerdChartLabel;
    private org.jdesktop.swingx.JXLabel lineChartLabel;
    private javax.swing.JButton printButton;
    private javax.swing.JTable rangesTabel;
    private javax.swing.JTextField secondRangeText;
    private javax.swing.JComboBox subjectCombo;
    private javax.swing.JComboBox testIdCombo;
    private javax.swing.JComboBox testTypeCombo;
    private javax.swing.JLabel testTypeLabel1;
    private javax.swing.JLabel testTypeLabel2;
    private javax.swing.JLabel testTypeLabel3;
    private javax.swing.JLabel testTypeLabel4;
    private javax.swing.JLabel testTypeLabel5;
    private javax.swing.JLabel testTypeLabel6;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
    private void fillSubjectCombo() throws SQLException, ClassNotFoundException {
        ArrayList<Subject> subjectList = SubjectController.getAllSubject();
        //subjectList.removeAllItems();
        for (Subject subject : subjectList) {
            subjectCombo.addItem(subject);

        }
    }

    private void fillTestIdCombo() throws SQLException, ClassNotFoundException {
        ArrayList<Test> testList = TestController.getTestId(classText.getText(), subjectCombo.getSelectedItem() + "", testTypeCombo.getSelectedItem() + "");
        //subjectList.removeAllItems();
        for (Test test : testList) {
            testIdCombo.addItem(test);
        }
    }
}
