/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dakmainstitute.view.managestudents;

import dakmainstitute.controller.*;
import dakmainstitute.model.*;
import dakmainstitute.view.AddSchoolForm;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Shashi
 */
public class AddStudentForm extends JInternalFrame {

    Date d;
    DateFormat timeInstance;

    /**
     * Creates new form AddStudentForm
     */
    public AddStudentForm() {
        //super("Add Student",true,true,true,true);
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//        try {       
//            UIManager.setLookAndFeel(new AcrylLookAndFeel());
//        } catch (UnsupportedLookAndFeelException ex) {
//            Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
       

        dobText.setDate(new Date(93, 01, 01));

        d = new Date();

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(d);
        dateText.setText(date);
        timeInstance = DateFormat.getTimeInstance(DateFormat.SHORT);

        try {
            fillSchoolCombo();
            fillSubjectCombo();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        districtButtonGroup = new javax.swing.ButtonGroup();
        classTypeButtonGroup = new javax.swing.ButtonGroup();
        genderButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        gederLabel = new javax.swing.JLabel();
        classTypeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        districLabel = new javax.swing.JLabel();
        indexNoLabel = new javax.swing.JLabel();
        districText = new javax.swing.JTextField();
        classTypeText = new javax.swing.JTextField();
        genderText = new javax.swing.JTextField();
        indexNotext = new javax.swing.JTextField();
        classLabel = new javax.swing.JLabel();
        subjectLabel = new javax.swing.JLabel();
        subjectCombo = new javax.swing.JComboBox();
        classText = new javax.swing.JTextField();
        dateText = new javax.swing.JTextField();
        mataraRadioButton = new javax.swing.JRadioButton();
        galleRadioButton = new javax.swing.JRadioButton();
        thangallaRadioButton = new javax.swing.JRadioButton();
        revisionButton = new javax.swing.JRadioButton();
        theoryButton = new javax.swing.JRadioButton();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        NICText = new javax.swing.JTextField();
        schoolLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        homeNumLabel = new javax.swing.JLabel();
        mobileNumLabel = new javax.swing.JLabel();
        mobileNumText = new javax.swing.JTextField();
        homeNumText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        NICLabel = new javax.swing.JLabel();
        tempAddressLabel = new javax.swing.JLabel();
        AddressText = new javax.swing.JTextField();
        dobLabel = new javax.swing.JLabel();
        schoolCombo = new javax.swing.JComboBox();
        addSchoolButton = new javax.swing.JButton();
        reloadButton = new javax.swing.JButton();
        dobText = new org.jdesktop.swingx.JXDatePicker();
        jPanel9 = new javax.swing.JPanel();
        guardianTabbedPane39 = new javax.swing.JTabbedPane();
        jPanel49 = new javax.swing.JPanel();
        fatherNameLabel = new javax.swing.JLabel();
        fNameText = new javax.swing.JTextField();
        fatherOccupationLabel = new javax.swing.JLabel();
        fOccuText = new javax.swing.JTextField();
        officeAddressLabel = new javax.swing.JLabel();
        fAddresstext = new javax.swing.JTextField();
        contactNumLabel = new javax.swing.JLabel();
        fContactNumText = new javax.swing.JTextField();
        officeNumLabel42 = new javax.swing.JLabel();
        fOfiiceNumText = new javax.swing.JTextField();
        jPanel50 = new javax.swing.JPanel();
        guardianNameLabel = new javax.swing.JLabel();
        gNameText = new javax.swing.JTextField();
        gOccuText = new javax.swing.JTextField();
        guardianOccupationLabel = new javax.swing.JLabel();
        gAddresstext = new javax.swing.JTextField();
        officeAddressLabel2 = new javax.swing.JLabel();
        gContactNumText = new javax.swing.JTextField();
        contactNumLabel2 = new javax.swing.JLabel();
        officeNumLabel2 = new javax.swing.JLabel();
        gOfiiceNumText = new javax.swing.JTextField();
        jPanel51 = new javax.swing.JPanel();
        mAddressText = new javax.swing.JLabel();
        motherNameLabel = new javax.swing.JLabel();
        mNameText = new javax.swing.JTextField();
        mOccuText = new javax.swing.JTextField();
        motherOccupationLabel = new javax.swing.JLabel();
        officeAddressLabel1 = new javax.swing.JLabel();
        mAddresstext = new javax.swing.JTextField();
        mContactNumText = new javax.swing.JTextField();
        contactNumLabel1 = new javax.swing.JLabel();
        officeNumLabel1 = new javax.swing.JLabel();
        mOfiiceNumText = new javax.swing.JTextField();
        cancelButton3 = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setToolTipText("Dakma Higer Education Center");

        jPanel1.setBackground(java.awt.Color.white);

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        jPanel2.setForeground(new java.awt.Color(51, 0, 51));

        gederLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        gederLabel.setText("Gender :");

        classTypeLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        classTypeLabel.setText("Class Type :");

        dateLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dateLabel.setText("Date       :");

        districLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        districLabel.setText("Distric     :");

        indexNoLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        indexNoLabel.setText("Index No :");

        districText.setEditable(false);
        districText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        districText.setFocusable(false);
        districText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districTextActionPerformed(evt);
            }
        });
        districText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                districTextKeyReleased(evt);
            }
        });

        classTypeText.setEditable(false);
        classTypeText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        classTypeText.setFocusable(false);
        classTypeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                classTypeTextKeyReleased(evt);
            }
        });

        genderText.setEditable(false);
        genderText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        genderText.setFocusable(false);
        genderText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTextActionPerformed(evt);
            }
        });
        genderText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                genderTextKeyReleased(evt);
            }
        });

        indexNotext.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        indexNotext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexNotextActionPerformed(evt);
            }
        });
        indexNotext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                indexNotextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                indexNotextKeyReleased(evt);
            }
        });

        classLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        classLabel.setText("Class :");

        subjectLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        subjectLabel.setText("Subject :");

        subjectCombo.setBackground(new java.awt.Color(153, 204, 255));
        subjectCombo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        subjectCombo.setForeground(new java.awt.Color(51, 70, 14));
        subjectCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectComboActionPerformed(evt);
            }
        });
        subjectCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subjectComboKeyPressed(evt);
            }
        });

        classText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        classText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classTextActionPerformed(evt);
            }
        });
        classText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                classTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                classTextKeyReleased(evt);
            }
        });

        dateText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextActionPerformed(evt);
            }
        });
        dateText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dateTextKeyPressed(evt);
            }
        });

        mataraRadioButton.setBackground(new java.awt.Color(255, 204, 204));
        districtButtonGroup.add(mataraRadioButton);
        mataraRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mataraRadioButton.setForeground(new java.awt.Color(51, 0, 51));
        mataraRadioButton.setText("Matara");
        mataraRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mataraRadioButtonActionPerformed(evt);
            }
        });

        galleRadioButton.setBackground(new java.awt.Color(255, 204, 204));
        districtButtonGroup.add(galleRadioButton);
        galleRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        galleRadioButton.setForeground(new java.awt.Color(51, 0, 51));
        galleRadioButton.setText("Galle");
        galleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galleRadioButtonActionPerformed(evt);
            }
        });

        thangallaRadioButton.setBackground(new java.awt.Color(255, 204, 204));
        districtButtonGroup.add(thangallaRadioButton);
        thangallaRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        thangallaRadioButton.setForeground(new java.awt.Color(51, 0, 51));
        thangallaRadioButton.setText("Thangalla");
        thangallaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thangallaRadioButtonActionPerformed(evt);
            }
        });

        revisionButton.setBackground(new java.awt.Color(255, 204, 204));
        classTypeButtonGroup.add(revisionButton);
        revisionButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        revisionButton.setForeground(new java.awt.Color(51, 0, 51));
        revisionButton.setText("Revision ");
        revisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revisionButtonActionPerformed(evt);
            }
        });

        theoryButton.setBackground(new java.awt.Color(255, 204, 204));
        classTypeButtonGroup.add(theoryButton);
        theoryButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        theoryButton.setForeground(new java.awt.Color(51, 0, 51));
        theoryButton.setText("Theory");
        theoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theoryButtonActionPerformed(evt);
            }
        });

        maleButton.setBackground(new java.awt.Color(255, 204, 204));
        genderButtonGroup.add(maleButton);
        maleButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        maleButton.setForeground(new java.awt.Color(51, 0, 51));
        maleButton.setText("Male");
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });

        femaleButton.setBackground(new java.awt.Color(255, 204, 204));
        genderButtonGroup.add(femaleButton);
        femaleButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        femaleButton.setForeground(new java.awt.Color(51, 0, 51));
        femaleButton.setText("Female");
        femaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(districLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(thangallaRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mataraRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addComponent(galleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(classTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(theoryButton)
                            .addComponent(revisionButton)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(indexNoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(districText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(indexNotext, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subjectLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(classLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(classText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(subjectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(gederLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(femaleButton)
                            .addComponent(maleButton))
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {classTypeText, districText, genderText});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(districLabel)
                            .addComponent(mataraRadioButton)
                            .addComponent(galleRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thangallaRadioButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleButton)
                            .addComponent(gederLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(femaleButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(revisionButton)
                            .addComponent(classTypeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(theoryButton)))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectLabel)
                    .addComponent(subjectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indexNotext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(districText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indexNoLabel))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateLabel)
                        .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(classText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(classLabel)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {classTypeText, districText, genderText});

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("   Register Student");

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));

        NICText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        NICText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NICTextActionPerformed(evt);
            }
        });
        NICText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NICTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NICTextKeyReleased(evt);
            }
        });

        schoolLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        schoolLabel.setText("School for A/L at present :");

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact", 0, 0, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(0, 51, 51))); // NOI18N

        homeNumLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        homeNumLabel.setText("Home Num :");

        mobileNumLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mobileNumLabel.setText("Mobile Num :");

        mobileNumText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mobileNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileNumTextActionPerformed(evt);
            }
        });
        mobileNumText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobileNumTextKeyReleased(evt);
            }
        });

        homeNumText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        homeNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeNumTextActionPerformed(evt);
            }
        });
        homeNumText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                homeNumTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mobileNumLabel)
                .addGap(18, 18, 18)
                .addComponent(mobileNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(homeNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homeNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeNumLabel)
                    .addComponent(mobileNumLabel)
                    .addComponent(mobileNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        nameText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextKeyReleased(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        nameLabel.setText("Name in full             :");

        NICLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        NICLabel.setText("National Identity Card #   :");

        tempAddressLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tempAddressLabel.setText("Address                  :");

        AddressText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        AddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTextActionPerformed(evt);
            }
        });

        dobLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dobLabel.setText("Date of Birth           :");

        schoolCombo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        schoolCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolComboActionPerformed(evt);
            }
        });
        schoolCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                schoolComboKeyPressed(evt);
            }
        });

        addSchoolButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        addSchoolButton.setForeground(new java.awt.Color(0, 51, 51));
        addSchoolButton.setText("Add new School");
        addSchoolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSchoolButtonActionPerformed(evt);
            }
        });

        reloadButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        reloadButton.setForeground(new java.awt.Color(0, 51, 51));
        reloadButton.setText("Reload");
        reloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonActionPerformed(evt);
            }
        });

        dobText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(tempAddressLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(dobLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dobText, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(NICLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NICText, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(schoolLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(schoolCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSchoolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempAddressLabel)
                    .addComponent(AddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabel)
                    .addComponent(dobText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NICLabel)
                    .addComponent(NICText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolLabel)
                    .addComponent(schoolCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSchoolButton)
                    .addComponent(reloadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel9.setBackground(java.awt.Color.white);
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 2, true));

        jPanel49.setBackground(java.awt.Color.white);
        jPanel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));

        fatherNameLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fatherNameLabel.setText("Father's Name         :");

        fNameText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTextActionPerformed(evt);
            }
        });

        fatherOccupationLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fatherOccupationLabel.setText("Father's Occupation :");

        fOccuText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fOccuText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fOccuTextActionPerformed(evt);
            }
        });

        officeAddressLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        officeAddressLabel.setText("Office Address         :");

        fAddresstext.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fAddresstext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fAddresstextActionPerformed(evt);
            }
        });

        contactNumLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        contactNumLabel.setText("Contact Num           :");

        fContactNumText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fContactNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fContactNumTextActionPerformed(evt);
            }
        });
        fContactNumText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fContactNumTextKeyReleased(evt);
            }
        });

        officeNumLabel42.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        officeNumLabel42.setText("Office Num               :");

        fOfiiceNumText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fOfiiceNumText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fOfiiceNumTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel49Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel49Layout.createSequentialGroup()
                        .addGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fatherNameLabel)
                            .addComponent(fatherOccupationLabel)
                            .addComponent(officeAddressLabel)
                            .addComponent(contactNumLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fContactNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fOccuText, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fAddresstext, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel49Layout.createSequentialGroup()
                        .addComponent(officeNumLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fOfiiceNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel49Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fatherNameLabel)
                    .addComponent(fNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fatherOccupationLabel)
                    .addComponent(fOccuText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(officeAddressLabel)
                    .addComponent(fAddresstext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contactNumLabel)
                    .addComponent(fContactNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(officeNumLabel42)
                    .addComponent(fOfiiceNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel49Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {contactNumLabel, fAddresstext, fContactNumText, fNameText, fOccuText, fatherNameLabel, fatherOccupationLabel, officeAddressLabel});

        guardianTabbedPane39.addTab("Father", jPanel49);

        jPanel50.setBackground(java.awt.Color.white);
        jPanel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));

        guardianNameLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        guardianNameLabel.setText("Guadian's Name         :");

        gNameText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        gNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gNameTextActionPerformed(evt);
            }
        });

        gOccuText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        gOccuText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gOccuTextActionPerformed(evt);
            }
        });

        guardianOccupationLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        guardianOccupationLabel.setText("Guadian's Occupation :");

        gAddresstext.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        gAddresstext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gAddresstextActionPerformed(evt);
            }
        });

        officeAddressLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        officeAddressLabel2.setText("Office Address           :");

        gContactNumText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        gContactNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gContactNumTextActionPerformed(evt);
            }
        });
        gContactNumText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gContactNumTextKeyReleased(evt);
            }
        });

        contactNumLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        contactNumLabel2.setText("Contact Num             :");

        officeNumLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        officeNumLabel2.setText("Office Num               :");

        gOfiiceNumText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        gOfiiceNumText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gOfiiceNumTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel50Layout = new javax.swing.GroupLayout(jPanel50);
        jPanel50.setLayout(jPanel50Layout);
        jPanel50Layout.setHorizontalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel50Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardianOccupationLabel)
                    .addComponent(guardianNameLabel)
                    .addComponent(officeAddressLabel2)
                    .addComponent(contactNumLabel2)
                    .addComponent(officeNumLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(gOfiiceNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gContactNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addComponent(gOccuText))
                    .addComponent(gAddresstext, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel50Layout.setVerticalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel50Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardianNameLabel)
                    .addComponent(gNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardianOccupationLabel)
                    .addComponent(gOccuText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(officeAddressLabel2)
                    .addComponent(gAddresstext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumLabel2)
                    .addComponent(gContactNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(officeNumLabel2)
                    .addComponent(gOfiiceNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        jPanel50Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {contactNumLabel2, gAddresstext, gContactNumText, gNameText, gOccuText, gOfiiceNumText, guardianNameLabel, guardianOccupationLabel, officeAddressLabel2, officeNumLabel2});

        guardianTabbedPane39.addTab("Guardian", jPanel50);

        jPanel51.setBackground(java.awt.Color.white);
        jPanel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel51.setForeground(new java.awt.Color(51, 0, 51));

        mAddressText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        motherNameLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        motherNameLabel.setText("Mother's Name         :");

        mNameText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNameTextActionPerformed(evt);
            }
        });

        mOccuText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mOccuText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOccuTextActionPerformed(evt);
            }
        });

        motherOccupationLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        motherOccupationLabel.setText("Mother's Occupation :");

        officeAddressLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        officeAddressLabel1.setText("Office Address         :");

        mAddresstext.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mAddresstext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddresstextActionPerformed(evt);
            }
        });

        mContactNumText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mContactNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mContactNumTextActionPerformed(evt);
            }
        });
        mContactNumText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mContactNumTextKeyReleased(evt);
            }
        });

        contactNumLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        contactNumLabel1.setText("Contact Num           :");

        officeNumLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        officeNumLabel1.setText("Office Num              :");

        mOfiiceNumText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mOfiiceNumText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mOfiiceNumTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel51Layout = new javax.swing.GroupLayout(jPanel51);
        jPanel51.setLayout(jPanel51Layout);
        jPanel51Layout.setHorizontalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel51Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel51Layout.createSequentialGroup()
                        .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(motherOccupationLabel)
                            .addComponent(motherNameLabel)
                            .addComponent(officeNumLabel1)
                            .addComponent(contactNumLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mAddresstext, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(mContactNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mOfiiceNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mOccuText, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(officeAddressLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel51Layout.setVerticalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel51Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(jPanel51Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motherNameLabel)
                    .addComponent(mNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motherOccupationLabel)
                    .addComponent(mOccuText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mAddresstext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(officeAddressLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumLabel1)
                    .addComponent(mContactNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mOfiiceNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(officeNumLabel1))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jPanel51Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {contactNumLabel1, mAddresstext, mContactNumText, mNameText, mOccuText, mOfiiceNumText, motherNameLabel, motherOccupationLabel, officeAddressLabel1, officeNumLabel1});

        guardianTabbedPane39.addTab("Mother", jPanel51);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guardianTabbedPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(guardianTabbedPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        cancelButton3.setBackground(new java.awt.Color(255, 153, 153));
        cancelButton3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        cancelButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dakmainstitute/icon/delete-26.png"))); // NOI18N
        cancelButton3.setText("Cancel");
        cancelButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton3ActionPerformed(evt);
            }
        });

        SaveButton.setBackground(new java.awt.Color(153, 153, 255));
        SaveButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dakmainstitute/icon/save-26.png"))); // NOI18N
        SaveButton.setText("Save");
        SaveButton.setEnabled(false);
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelButton3)
                .addGap(204, 204, 204))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(517, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        String indexNo = districText.getText() + "" + classTypeText.getText() + "" + genderText.getText() + "" + indexNotext.getText();
        Date d = dobText.getDate();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String date = df.format(new Date());

        String nic = NICText.getText();
        String name = nameText.getText();
        String dob = df.format(d);
        String address = AddressText.getText();
        String school = ((School) schoolCombo.getSelectedItem()).getSchoolId();
        String mobileNum = mobileNumText.getText();
        String homeNum = homeNumText.getText();
        String gender = null;

        if (maleButton.isSelected()) {
            gender = "Male";
        } else if (femaleButton.isSelected()) {
            gender = "Female";
        }

        String distric = null;

        if (mataraRadioButton.isSelected()) {
            distric = "Matara";
        } else if (galleRadioButton.isSelected()) {
            distric = "Galle";
        } else if (thangallaRadioButton.isSelected()) {
            distric = "Thangalla";
        }

        String classes = classText.getText();
        String subject = subjectCombo.getSelectedItem() + "";

        Student student = new Student(indexNo, nic, name, date, address, dob, school, mobileNum, homeNum, gender, distric, classes, subject);
        int resStudent = 0;
        int resMother = 0;
        int resFather = 0;
        int resGuardian = 0;

        try {
            resStudent = StudentController.addStudent(student);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (!mNameText.getText().isEmpty()) {
            Mother mother = new Mother(indexNo, mNameText.getText(), mOccuText.getText(), mAddresstext.getText(), mContactNumText.getText(), mOfiiceNumText.getText());
            try {
                resMother = MotherController.addMother(mother);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (!fNameText.getText().isEmpty()) {
            Father father = new Father(indexNo, fNameText.getText(), fOccuText.getText(), fAddresstext.getText(), fContactNumText.getText(), fOfiiceNumText.getText());
            try {
                resFather = FatherController.addFather(father);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (!gNameText.getText().isEmpty()) {
            Guardian guardian = new Guardian(indexNo, gNameText.getText(), gOccuText.getText(), gAddresstext.getText(), gContactNumText.getText(), gOfiiceNumText.getText());
            try {
                resGuardian = GuardianController.addGuardian(guardian);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if ((resStudent > 0 || resMother > 0 || resFather > 0 || resGuardian > 0)) {
            JOptionPane.showMessageDialog(this, "Student details added successful...");
        } else {
            JOptionPane.showMessageDialog(this, "Student details added fail...");
        }
        try {
            refresh();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void cancelButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButton3ActionPerformed

    private void gOfiiceNumTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gOfiiceNumTextKeyReleased
        String txt = gOfiiceNumText.getText();
        int caretPosition = gOfiiceNumText.getCaretPosition();
        if (!txt.matches("^[0-9]*{10,}+$")) {
            gOfiiceNumText.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            gOfiiceNumText.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_gOfiiceNumTextKeyReleased

    private void gContactNumTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gContactNumTextKeyReleased
        String txt = gContactNumText.getText();
        int caretPosition = gContactNumText.getCaretPosition();
        if (!txt.matches("^[0-9]*{10,}+$")) {
            gContactNumText.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            gContactNumText.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_gContactNumTextKeyReleased

    private void gContactNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gContactNumTextActionPerformed
        gOfiiceNumText.requestFocus();
    }//GEN-LAST:event_gContactNumTextActionPerformed

    private void gAddresstextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gAddresstextActionPerformed
        gContactNumText.requestFocus();
    }//GEN-LAST:event_gAddresstextActionPerformed

    private void gOccuTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gOccuTextActionPerformed
        gAddresstext.requestFocus();
    }//GEN-LAST:event_gOccuTextActionPerformed

    private void gNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gNameTextActionPerformed
        gOccuText.requestFocus();
    }//GEN-LAST:event_gNameTextActionPerformed

    private void mOfiiceNumTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mOfiiceNumTextKeyReleased
        String txt = mOfiiceNumText.getText();
        int caretPosition = mOfiiceNumText.getCaretPosition();
        if (!txt.matches("^[0-9]*{10,}+$")) {
            mOfiiceNumText.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            mOfiiceNumText.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_mOfiiceNumTextKeyReleased

    private void mContactNumTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mContactNumTextKeyReleased
        String txt = mContactNumText.getText();
        int caretPosition = mContactNumText.getCaretPosition();
        if (!txt.matches("^[0-9]*{10,}+$")) {
            mContactNumText.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            mContactNumText.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_mContactNumTextKeyReleased

    private void mContactNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mContactNumTextActionPerformed
        mOfiiceNumText.requestFocus();
    }//GEN-LAST:event_mContactNumTextActionPerformed

    private void mNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNameTextActionPerformed
        mOccuText.requestFocus();
    }//GEN-LAST:event_mNameTextActionPerformed

    private void mOccuTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOccuTextActionPerformed
        mAddresstext.requestFocus();
    }//GEN-LAST:event_mOccuTextActionPerformed

    private void mAddresstextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAddresstextActionPerformed
        mContactNumText.requestFocus();
    }//GEN-LAST:event_mAddresstextActionPerformed

    private void fContactNumTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fContactNumTextKeyReleased
        String txt = fContactNumText.getText();
        int caretPosition = fContactNumText.getCaretPosition();
        if (!txt.matches("^[0-9]*{10,}+$")) {
            fContactNumText.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            fContactNumText.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_fContactNumTextKeyReleased

    private void fContactNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fContactNumTextActionPerformed
        fOfiiceNumText.requestFocus();
    }//GEN-LAST:event_fContactNumTextActionPerformed

    private void fNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTextActionPerformed
        fOccuText.requestFocus();
    }//GEN-LAST:event_fNameTextActionPerformed

    private void fOccuTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fOccuTextActionPerformed
        fAddresstext.requestFocus();
    }//GEN-LAST:event_fOccuTextActionPerformed

    private void fAddresstextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fAddresstextActionPerformed
        fContactNumText.requestFocus();
    }//GEN-LAST:event_fAddresstextActionPerformed

    private void dobTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTextActionPerformed
        NICText.requestFocus();
    }//GEN-LAST:event_dobTextActionPerformed

    private void reloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonActionPerformed
        try {
            fillSchoolCombo();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reloadButtonActionPerformed

    private void addSchoolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSchoolButtonActionPerformed
        new AddSchoolForm().setVisible(true);
    }//GEN-LAST:event_addSchoolButtonActionPerformed

    private void schoolComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_schoolComboKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            mobileNumText.requestFocus();
        }
    }//GEN-LAST:event_schoolComboKeyPressed

    private void schoolComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolComboActionPerformed

    }//GEN-LAST:event_schoolComboActionPerformed

    private void AddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTextActionPerformed
        dobText.requestFocus();
    }//GEN-LAST:event_AddressTextActionPerformed

    private void nameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyReleased
        String txt = nameText.getText();
        int caretPosition = nameText.getCaretPosition();
        if (caretPosition == 1) {
            String st = txt.toUpperCase();
            nameText.setText(st);
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            if (nameText.getCaretPosition() == 1) {
                String st = nameText.getText().toUpperCase();
                nameText.setText(st);
            }
            //            String st = txt.toUpperCase();
            //            nameText.setText(st);
        }

        
        try {
            saveButtonSetEnabled();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nameTextKeyReleased

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        AddressText.requestFocus();
    }//GEN-LAST:event_nameTextActionPerformed

    private void homeNumTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homeNumTextKeyReleased
        String txt = homeNumText.getText();
        int caretPosition = homeNumText.getCaretPosition();
        if (!txt.matches("^[0-9]*{10,}+$")) {
            homeNumText.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            homeNumText.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_homeNumTextKeyReleased

    private void homeNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeNumTextActionPerformed
        mNameText.requestFocus();
    }//GEN-LAST:event_homeNumTextActionPerformed

    private void mobileNumTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileNumTextKeyReleased
        String txt = mobileNumText.getText();
        int caretPosition = mobileNumText.getCaretPosition();
        if (!txt.matches("^[0-9]*{10}$")) {
            mobileNumText.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            mobileNumText.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_mobileNumTextKeyReleased

    private void mobileNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileNumTextActionPerformed
        homeNumText.requestFocus();
    }//GEN-LAST:event_mobileNumTextActionPerformed

    private void NICTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NICTextKeyReleased
        String txt = NICText.getText();
        int caretPosition = NICText.getCaretPosition();
        if (!txt.matches("^[0-9]*{9,}+$")) {
            NICText.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            NICText.setCaretPosition(caretPosition - 1);
        }
        try {
            saveButtonSetEnabled();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NICTextKeyReleased

    private void NICTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NICTextKeyPressed
        if (evt.getKeyCode() == 10) {
            String nic = NICText.getText();
            NICText.setText(nic + "V");
            NICText.requestFocus();
        }
    }//GEN-LAST:event_NICTextKeyPressed

    private void NICTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NICTextActionPerformed

        schoolCombo.requestFocus();
    }//GEN-LAST:event_NICTextActionPerformed

    private void femaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleButtonActionPerformed
        if (femaleButton.isSelected()) {
            genderText.setText("G");
            indexNotext.requestFocus();
        }
    }//GEN-LAST:event_femaleButtonActionPerformed

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
        if (maleButton.isSelected()) {
            genderText.setText("B");
            indexNotext.requestFocus();
        }
    }//GEN-LAST:event_maleButtonActionPerformed

    private void theoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theoryButtonActionPerformed
        if (theoryButton.isSelected()) {
            classTypeText.setText("T");
        }
    }//GEN-LAST:event_theoryButtonActionPerformed

    private void revisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revisionButtonActionPerformed
        if (revisionButton.isSelected()) {
            classTypeText.setText("R");
        }
    }//GEN-LAST:event_revisionButtonActionPerformed

    private void thangallaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thangallaRadioButtonActionPerformed
        if (thangallaRadioButton.isSelected()) {
            districText.setText("T");
        }
    }//GEN-LAST:event_thangallaRadioButtonActionPerformed

    private void galleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galleRadioButtonActionPerformed
        if (galleRadioButton.isSelected()) {
            districText.setText("G");
        }
    }//GEN-LAST:event_galleRadioButtonActionPerformed

    private void mataraRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mataraRadioButtonActionPerformed
        if (mataraRadioButton.isSelected()) {
            districText.setText("M");
        }
    }//GEN-LAST:event_mataraRadioButtonActionPerformed

    private void dateTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateTextKeyPressed
        if (evt.getKeyCode() == 10) {
            subjectCombo.requestFocus();
        }
    }//GEN-LAST:event_dateTextKeyPressed

    private void dateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextActionPerformed

    }//GEN-LAST:event_dateTextActionPerformed

    private void classTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classTextKeyReleased
        String txt = classText.getText();
        int caretPosition = classText.getCaretPosition();
        if (!txt.matches("^[0-9]*{4,}+$")) {
            classText.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            classText.setCaretPosition(caretPosition - 1);
        }
        try {
            saveButtonSetEnabled();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_classTextKeyReleased

    private void classTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classTextKeyPressed
        if (evt.getKeyCode() == 10) {
            String clz = classText.getText();
            classText.setText(clz + "A/L");
            nameText.requestFocus();
        }
    }//GEN-LAST:event_classTextKeyPressed

    private void classTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classTextActionPerformed

    }//GEN-LAST:event_classTextActionPerformed

    private void subjectComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subjectComboKeyPressed
        if (evt.getKeyCode() == 10) {
            classText.requestFocus();
        }
    }//GEN-LAST:event_subjectComboKeyPressed

    private void subjectComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectComboActionPerformed

    }//GEN-LAST:event_subjectComboActionPerformed

    private void indexNotextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_indexNotextKeyReleased
        String txt = indexNotext.getText();
        int caretPosition = indexNotext.getCaretPosition();
        if (!txt.matches("^[0-9]*{4,}+$")) {
            indexNotext.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            indexNotext.setCaretPosition(caretPosition - 1);
        }
        try {
            saveButtonSetEnabled();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_indexNotextKeyReleased

    private void indexNotextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_indexNotextKeyPressed
        if (evt.getKeyCode() == 10) {
            String indexNo = districText.getText() + classTypeText.getText() + genderText.getText() + indexNotext.getText();
            try {

                if (StudentController.isStudentAvailable(indexNo)) {
                    JOptionPane.showMessageDialog(this, "This Student is Available..");

                } else {
                    dateText.requestFocus();
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_indexNotextKeyPressed

    private void indexNotextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexNotextActionPerformed

    }//GEN-LAST:event_indexNotextActionPerformed

    private void genderTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTextActionPerformed

    }//GEN-LAST:event_genderTextActionPerformed

    private void districTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districTextActionPerformed

    }//GEN-LAST:event_districTextActionPerformed

    private void fOfiiceNumTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fOfiiceNumTextKeyReleased
        
    }//GEN-LAST:event_fOfiiceNumTextKeyReleased

    private void districTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_districTextKeyReleased
        try {
            saveButtonSetEnabled();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_districTextKeyReleased

    private void classTypeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classTypeTextKeyReleased
        try {
            saveButtonSetEnabled();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_classTypeTextKeyReleased

    private void genderTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genderTextKeyReleased
        try {
            saveButtonSetEnabled();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_genderTextKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudentForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressText;
    private javax.swing.JLabel NICLabel;
    private javax.swing.JTextField NICText;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton addSchoolButton;
    private javax.swing.JButton cancelButton3;
    private javax.swing.JLabel classLabel;
    private javax.swing.JTextField classText;
    private javax.swing.ButtonGroup classTypeButtonGroup;
    private javax.swing.JLabel classTypeLabel;
    private javax.swing.JTextField classTypeText;
    private javax.swing.JLabel contactNumLabel;
    private javax.swing.JLabel contactNumLabel1;
    private javax.swing.JLabel contactNumLabel2;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateText;
    private javax.swing.JLabel districLabel;
    private javax.swing.JTextField districText;
    private javax.swing.ButtonGroup districtButtonGroup;
    private javax.swing.JLabel dobLabel;
    private org.jdesktop.swingx.JXDatePicker dobText;
    private javax.swing.JTextField fAddresstext;
    private javax.swing.JTextField fContactNumText;
    private javax.swing.JTextField fNameText;
    private javax.swing.JTextField fOccuText;
    private javax.swing.JTextField fOfiiceNumText;
    private javax.swing.JLabel fatherNameLabel;
    private javax.swing.JLabel fatherOccupationLabel;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JTextField gAddresstext;
    private javax.swing.JTextField gContactNumText;
    private javax.swing.JTextField gNameText;
    private javax.swing.JTextField gOccuText;
    private javax.swing.JTextField gOfiiceNumText;
    private javax.swing.JRadioButton galleRadioButton;
    private javax.swing.JLabel gederLabel;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JTextField genderText;
    private javax.swing.JLabel guardianNameLabel;
    private javax.swing.JLabel guardianOccupationLabel;
    private javax.swing.JTabbedPane guardianTabbedPane39;
    private javax.swing.JLabel homeNumLabel;
    private javax.swing.JTextField homeNumText;
    private javax.swing.JLabel indexNoLabel;
    private javax.swing.JTextField indexNotext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mAddressText;
    private javax.swing.JTextField mAddresstext;
    private javax.swing.JTextField mContactNumText;
    private javax.swing.JTextField mNameText;
    private javax.swing.JTextField mOccuText;
    private javax.swing.JTextField mOfiiceNumText;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JRadioButton mataraRadioButton;
    private javax.swing.JLabel mobileNumLabel;
    private javax.swing.JTextField mobileNumText;
    private javax.swing.JLabel motherNameLabel;
    private javax.swing.JLabel motherOccupationLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel officeAddressLabel;
    private javax.swing.JLabel officeAddressLabel1;
    private javax.swing.JLabel officeAddressLabel2;
    private javax.swing.JLabel officeNumLabel1;
    private javax.swing.JLabel officeNumLabel2;
    private javax.swing.JLabel officeNumLabel42;
    private javax.swing.JButton reloadButton;
    private javax.swing.JRadioButton revisionButton;
    private javax.swing.JComboBox schoolCombo;
    private javax.swing.JLabel schoolLabel;
    private javax.swing.JComboBox subjectCombo;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JLabel tempAddressLabel;
    private javax.swing.JRadioButton thangallaRadioButton;
    private javax.swing.JRadioButton theoryButton;
    // End of variables declaration//GEN-END:variables

    private void fillSchoolCombo() throws SQLException, ClassNotFoundException {
        ArrayList<School> schoolList = SchoolController.getAllSchool();
        schoolCombo.removeAllItems();
        for (School school : schoolList) {
            schoolCombo.addItem(school);

        }
    }

    private void fillSubjectCombo() throws SQLException, ClassNotFoundException {
        ArrayList<Subject> subjectList = SubjectController.getAllSubject();
        for (Subject subject : subjectList) {
            subjectCombo.addItem(subject);

        }
    }
    private void saveButtonSetEnabled() throws SQLException, ClassNotFoundException {
        boolean b=districText.getText().isEmpty()|| classTypeText.getText().isEmpty() || 
                genderText.getText().isEmpty() || indexNotext.getText().isEmpty() || 
                classText.getText().isEmpty() || nameText.getText().isEmpty() || 
                NICText.getText().isEmpty();
        if(b==true){
            SaveButton.setEnabled(false);
        }else{
            SaveButton.setEnabled(true);
        }
    }

    private void refresh() throws SQLException, ClassNotFoundException {
        districText.setText("");
        classTypeText.setText("");
        genderText.setText("");
        indexNotext.setText("");
        classText.setText("");
        nameText.setText("");
        AddressText.setText("");
        NICText.setText("");
        mobileNumText.setText("");
        homeNumText.setText("");
        mNameText.setText("");
        mAddresstext.setText("");
        mOccuText.setText("");
        mContactNumText.setText("");
        mOfiiceNumText.setText("");
        fNameText.setText("");
        fAddresstext.setText("");
        fOccuText.setText("");
        fContactNumText.setText("");
        fOfiiceNumText.setText("");
        gNameText.setText("");
        gAddresstext.setText("");
        gOccuText.setText("");
        gContactNumText.setText("");
        gOfiiceNumText.setText("");
        fillSubjectCombo();
        fillSchoolCombo();
    }
}
