/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dakmainstitute.view.managestudents;

import dakmainstitute.controller.FatherController;
import dakmainstitute.controller.GuardianController;
import dakmainstitute.controller.MotherController;
import dakmainstitute.controller.StudentController;
import dakmainstitute.controller.TestController;
import dakmainstitute.model.Father;
import dakmainstitute.model.Guardian;
import dakmainstitute.model.Mother;
import dakmainstitute.model.Student;
import dakmainstitute.model.Test;
import dakmainstitute.view.managetest.viewTestMarks;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Shashi
 */
public class ViewStudent extends javax.swing.JFrame {

    /**
     * Creates new form ViewStudent
     */
    public ViewStudent(Student student) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        indexNoLabelText.setText(student.getIndexNo());
        ArrayList<Student> students = null;
        try {
            students = StudentController.getAllDetails(indexNoLabelText.getText());
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(viewTestMarks.class.getName()).log(Level.SEVERE, null, ex);
        }
        nameLabelText1.setText(students.get(0).getStudentName());
        addressText1.setText(students.get(0).getAddress());
        dobText.setText(students.get(0).getDateOfBirth());
        NICText1.setText(students.get(0).getNic());
        schoolText.setText(students.get(0).getSchools().getSchoolName());
        mobileText.setText(students.get(0).getMobileNum());
        homeNumText.setText(students.get(0).getHomeNum());

        ArrayList<Mother> mother = null;
        try {
            mother = MotherController.getAllDetails(indexNoLabelText.getText());
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(viewTestMarks.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!mother.isEmpty()) {
            motherNameLabel1.setText(mother.get(0).getMotherName());
            mOcuuText.setText(mother.get(0).getOccupation());
            mAddressText.setText(mother.get(0).getOfficeAddress());
            mMobileText.setText(mother.get(0).getMobileNum());
            mOfficeNumText.setText(mother.get(0).getOfficeNum());
        }

        ArrayList<Father> father = null;
        try {
            father = FatherController.getAllDetails(indexNoLabelText.getText());
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(viewTestMarks.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!father.isEmpty()) {
            fatherNameText.setText(father.get(0).getFatherName());
            fOcuuText.setText(father.get(0).getOccupation());
            fAddressText.setText(father.get(0).getOfficeAddress());
            fMobileText.setText(father.get(0).getMobileNum());
            fOfficeNumText.setText(father.get(0).getOfficeNum());
        }

        ArrayList<Guardian> guardian = null;
        try {
            guardian = GuardianController.getAllDetails(indexNoLabelText.getText());
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(viewTestMarks.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!guardian.isEmpty()) {
            gNameText.setText(guardian.get(0).getGuardianName());
            gOcuuText.setText(guardian.get(0).getOccupation());
            gAddressText.setText(guardian.get(0).getOfficeAddress());
            gMobileText.setText(guardian.get(0).getMobileNum());
            gOfficeNumText.setText(guardian.get(0).getOfficeNum());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        titleLabe = new javax.swing.JLabel();
        indexNoLabelText = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        schoolLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        homeNumLabel = new javax.swing.JLabel();
        mobileNumLabel = new javax.swing.JLabel();
        mobileText = new javax.swing.JLabel();
        homeNumText = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        NICLabel = new javax.swing.JLabel();
        tempAddressLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        dobText = new javax.swing.JLabel();
        nameLabelText1 = new javax.swing.JLabel();
        addressText1 = new javax.swing.JLabel();
        schoolText = new javax.swing.JLabel();
        NICText1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        indexNoLabel1 = new javax.swing.JLabel();
        guardianTabbedPane = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        officeNumLabel = new javax.swing.JLabel();
        contactNumLabel = new javax.swing.JLabel();
        fatherNameLabel = new javax.swing.JLabel();
        officeAddressLabel = new javax.swing.JLabel();
        fatherOccupationLabel = new javax.swing.JLabel();
        fAddressText = new javax.swing.JLabel();
        fOcuuText = new javax.swing.JLabel();
        fatherNameText = new javax.swing.JLabel();
        fMobileText = new javax.swing.JLabel();
        fOfficeNumText = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        officeAddressLabel2 = new javax.swing.JLabel();
        guardianOccupationLabel = new javax.swing.JLabel();
        guardianNameLabel = new javax.swing.JLabel();
        contactNumLabel2 = new javax.swing.JLabel();
        officeNumLabel2 = new javax.swing.JLabel();
        gAddressText = new javax.swing.JLabel();
        gOcuuText = new javax.swing.JLabel();
        gNameText = new javax.swing.JLabel();
        gMobileText = new javax.swing.JLabel();
        gOfficeNumText = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        motherNameLabel = new javax.swing.JLabel();
        motherOccupationLabel = new javax.swing.JLabel();
        officeAddressLabel1 = new javax.swing.JLabel();
        contactNumLabel1 = new javax.swing.JLabel();
        officeNumLabel1 = new javax.swing.JLabel();
        motherNameLabel1 = new javax.swing.JLabel();
        mOcuuText = new javax.swing.JLabel();
        mAddressText = new javax.swing.JLabel();
        mAddressText1 = new javax.swing.JLabel();
        mMobileText = new javax.swing.JLabel();
        mOfficeNumText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dakma Higher Education Center");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        titleLabe.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        titleLabe.setIcon(new javax.swing.ImageIcon("F:\\NetBeans Project\\icon\\cart113.gif")); // NOI18N
        titleLabe.setText("      Student Details ");

        indexNoLabelText.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        schoolLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        schoolLabel1.setText("School for A/L at present :");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact", 0, 0, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(0, 51, 51))); // NOI18N

        homeNumLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        homeNumLabel.setText("Home Num :");

        mobileNumLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        mobileNumLabel.setText("Mobile Num :");

        mobileText.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        homeNumText.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mobileNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mobileText, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mobileText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeNumText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(mobileNumLabel)))
        );

        nameLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        nameLabel.setText("Name in full            :");

        NICLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        NICLabel.setText("National Identity Card #   :");

        tempAddressLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tempAddressLabel.setText("Address                 :");

        dobLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dobLabel.setText("Date of Birth          :");

        dobText.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        nameLabelText1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        addressText1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        schoolText.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        NICText1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(schoolLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(schoolText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(NICLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NICText1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(tempAddressLabel)
                            .addComponent(dobLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dobText, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressText1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabelText1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(nameLabelText1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tempAddressLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dobLabel))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressText1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dobText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NICLabel)
                    .addComponent(NICText1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schoolLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(schoolText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(236, 252, 252));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        indexNoLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        indexNoLabel1.setText("Index No           :");

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));

        officeNumLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        officeNumLabel.setText("Office Num              :");

        contactNumLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        contactNumLabel.setText("Contact Num           :");

        fatherNameLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fatherNameLabel.setText("Father's Name         :");

        officeAddressLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        officeAddressLabel.setText("Office Address         :");

        fatherOccupationLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        fatherOccupationLabel.setText("Father's Occupation :");

        fAddressText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        fOcuuText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        fatherNameText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        fMobileText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        fOfficeNumText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fatherNameLabel)
                    .addComponent(fatherOccupationLabel)
                    .addComponent(officeAddressLabel)
                    .addComponent(contactNumLabel)
                    .addComponent(officeNumLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fatherNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fOcuuText, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fMobileText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fOfficeNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fatherNameLabel)
                    .addComponent(fatherNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fOcuuText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatherOccupationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(officeAddressLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fAddressText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactNumLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fMobileText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(officeNumLabel))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fOfficeNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {contactNumLabel, fAddressText, fMobileText, fOcuuText, fOfficeNumText, fatherNameLabel, fatherNameText, fatherOccupationLabel, officeAddressLabel, officeNumLabel});

        guardianTabbedPane.addTab("Father", new javax.swing.ImageIcon("F:\\NetBeans Project\\icon\\hand_computermouse_do_a_sw.gif"), jPanel7); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));

        officeAddressLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        officeAddressLabel2.setText("Office Address           :");

        guardianOccupationLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        guardianOccupationLabel.setText("Guadian's Occupation :");

        guardianNameLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        guardianNameLabel.setText("Guadian's Name         :");

        contactNumLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        contactNumLabel2.setText("Contact Num             :");

        officeNumLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        officeNumLabel2.setText("Office Num                :");

        gAddressText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        gOcuuText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        gNameText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        gMobileText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        gOfficeNumText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(guardianOccupationLabel)
                            .addComponent(officeNumLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gOcuuText, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gOfficeNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(guardianNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(contactNumLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gMobileText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(officeAddressLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {contactNumLabel2, guardianNameLabel, guardianOccupationLabel, officeAddressLabel2, officeNumLabel2});

        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardianNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardianOccupationLabel)
                    .addComponent(gOcuuText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(officeAddressLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gMobileText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNumLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(officeNumLabel2)
                    .addComponent(gOfficeNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {contactNumLabel2, gAddressText, gMobileText, gNameText, gOcuuText, gOfficeNumText, guardianNameLabel, guardianOccupationLabel, officeAddressLabel2, officeNumLabel2});

        guardianTabbedPane.addTab("Guardian", new javax.swing.ImageIcon("F:\\NetBeans Project\\icon\\hand_computermouse_do_a_sw.gif"), jPanel8); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setForeground(new java.awt.Color(51, 0, 51));

        motherNameLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        motherNameLabel.setText("Mother's Name         :");

        motherOccupationLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        motherOccupationLabel.setText("Mother's Occupation :");

        officeAddressLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        officeAddressLabel1.setText("Office Address         :");

        contactNumLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        contactNumLabel1.setText("Contact Num           :");

        officeNumLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        officeNumLabel1.setText("Office Num              :");

        motherNameLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mOcuuText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mAddressText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mAddressText1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mMobileText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        mOfficeNumText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(officeNumLabel1)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(motherNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(motherNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mOfficeNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(officeAddressLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(motherOccupationLabel)
                        .addGap(7, 7, 7)
                        .addComponent(mOcuuText, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(contactNumLabel1)
                        .addGap(9, 9, 9)
                        .addComponent(mMobileText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap(189, Short.MAX_VALUE)
                    .addComponent(mAddressText1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motherNameLabel)
                    .addComponent(motherNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motherOccupationLabel)
                    .addComponent(mOcuuText, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(officeAddressLabel1)
                    .addComponent(mAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contactNumLabel1)
                    .addComponent(mMobileText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mOfficeNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(officeNumLabel1))
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(mAddressText1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(126, Short.MAX_VALUE)))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {contactNumLabel1, mAddressText, mMobileText, mOcuuText, mOfficeNumText, motherNameLabel, motherNameLabel1, motherOccupationLabel, officeAddressLabel1, officeNumLabel1});

        guardianTabbedPane.addTab("Mother", new javax.swing.ImageIcon("F:\\NetBeans Project\\icon\\hand_computermouse_do_a_sw.gif"), jPanel6); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(guardianTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLabe)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(indexNoLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(indexNoLabelText, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titleLabe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(indexNoLabelText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indexNoLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardianTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 130, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NICLabel;
    private javax.swing.JLabel NICText1;
    private javax.swing.JLabel addressText1;
    private javax.swing.JLabel contactNumLabel;
    private javax.swing.JLabel contactNumLabel1;
    private javax.swing.JLabel contactNumLabel2;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel dobText;
    private javax.swing.JLabel fAddressText;
    private javax.swing.JLabel fMobileText;
    private javax.swing.JLabel fOcuuText;
    private javax.swing.JLabel fOfficeNumText;
    private javax.swing.JLabel fatherNameLabel;
    private javax.swing.JLabel fatherNameText;
    private javax.swing.JLabel fatherOccupationLabel;
    private javax.swing.JLabel gAddressText;
    private javax.swing.JLabel gMobileText;
    private javax.swing.JLabel gNameText;
    private javax.swing.JLabel gOcuuText;
    private javax.swing.JLabel gOfficeNumText;
    private javax.swing.JLabel guardianNameLabel;
    private javax.swing.JLabel guardianOccupationLabel;
    private javax.swing.JTabbedPane guardianTabbedPane;
    private javax.swing.JLabel homeNumLabel;
    private javax.swing.JLabel homeNumText;
    private javax.swing.JLabel indexNoLabel1;
    private javax.swing.JLabel indexNoLabelText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mAddressText;
    private javax.swing.JLabel mAddressText1;
    private javax.swing.JLabel mMobileText;
    private javax.swing.JLabel mOcuuText;
    private javax.swing.JLabel mOfficeNumText;
    private javax.swing.JLabel mobileNumLabel;
    private javax.swing.JLabel mobileText;
    private javax.swing.JLabel motherNameLabel;
    private javax.swing.JLabel motherNameLabel1;
    private javax.swing.JLabel motherOccupationLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabelText1;
    private javax.swing.JLabel officeAddressLabel;
    private javax.swing.JLabel officeAddressLabel1;
    private javax.swing.JLabel officeAddressLabel2;
    private javax.swing.JLabel officeNumLabel;
    private javax.swing.JLabel officeNumLabel1;
    private javax.swing.JLabel officeNumLabel2;
    private javax.swing.JLabel schoolLabel1;
    private javax.swing.JLabel schoolText;
    private javax.swing.JLabel tempAddressLabel;
    private javax.swing.JLabel titleLabe;
    // End of variables declaration//GEN-END:variables
}
